---
- repo: https://github.com/pre-commit/pre-commit-hooks
  sha: v0.9.1
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-ast
    - id: check-merge-conflict
    - id: flake8
- repo: https://github.com/detailyang/pre-commit-shell
  sha: 1.0.2
  hooks:
    - id: shell-lint
      files: 'bin/*'
